name: Check Action Metadata

# See: https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-action-metadata.yml"
      - "action.yml"
  pull_request:
    paths:
      - ".github/workflows/check-action-metadata.yml"
      - "action.yml"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage from changes to the JSON schema.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    env:
      JSON_SCHEMA_FOLDER: etc/github-action-json-schema
      JSON_SCHEMA_FILENAME: github-action.json

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v2

      - name: Download JSON schema for action.yml
        uses: carlosperate/download-file-action@v1.1.0
        with:
          # See: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-action.json
          file-url: https://json.schemastore.org/github-action
          location: ${{ env.JSON_SCHEMA_FOLDER }}
          file-name: ${{ env.JSON_SCHEMA_FILENAME }}

      - name: Install JSON schema validator
        run: sudo npm install --global ajv-cli

      - name: Validate action.yml
        # See: https://github.com/ajv-validator/ajv-cli#readme
        run: ajv --strict=false -s "${{ env.JSON_SCHEMA_FOLDER }}/${{ env.JSON_SCHEMA_FILENAME }}" -d action.yml
