name: Check Shell Scripts

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/check-shell.yml"
      - "**.sh"
  pull_request:
    paths:
      - ".github/workflows/check-shell.yml"
      - "**.sh"
  schedule:
    # Run every Tuesday at 8 AM UTC to catch breakage caused by new checks added to ShellCheck.
    - cron: "0 8 * * TUE"
  workflow_dispatch:
  repository_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: ShellCheck
        uses: azohra/shell-linter@latest
